[package]
name = "mc_project"
version = "0.2.1"
edition = "2021"

[workspace]
members = ["server", "common", "client", "macros"]

[lib]
name = "common"
path = "./common/"

[[bin]]
name = "client"
path = "./client/"

[[bin]]
name = "server"
path = "./server/"


