version: '3'

services:
  mc_server:
    image: mc_image
    ports:
      - "25565:25565" # Minecraft server port
      - "25560:25560" # Second port, adjust as needed
    environment:
      - EULA=TRUE # Example environment variable, accept EULA for Minecraft
    restart: always
